### ISSUE TITLE
Port 25566 not open

### ISSUE THREAD

**Issue by DannielDVH** [K-4U/serverQueryExtender#4]
Hi, i added the mod everything fine the server works but i tried to use the PHP viewer, didn t work so i thinked to check if the port is open and is not.
Shouldn t activate itself?

Edit: Tryed even with 25565 same thing, i tryed even with the python version
The console gives me after a while that:
`[20:39:38] [Query Listener #42/INFO] [SQE]: Packet len 7 [/86.126.23.76:5044]
[20:39:38] [Query Listener #42/INFO] [SQE]: Packet '09' [/86.126.23.76:5044]
[20:39:38] [Query Listener #42/INFO] [SQE]: Challenge [/86.126.23.76:5044]
[20:39:39] [Query Listener #42/INFO] [SQE]: Packet len 11 [/86.126.23.76:5044]
[20:39:39] [Query Listener #42/INFO] [SQE]: Packet '08' [/86.126.23.76:5044]
[20:39:39] [Query Listener #42/INFO] [SQE]: Asked for the special packet!
[20:39:39] [Query Listener #42/INFO] [SQE]: RECV:
[20:39:39] [Query Listener #42/INFO] [SQE]: closeSocket: java.net.DatagramSocket@52700001
Exception in thread "Query Listener #42" [20:39:39] [Query Listener #42/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NoClassDefFoundError: k4unl/minecraft/k4lib/network/EnumQueryValues
[20:39:39] [Query Listener #42/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at k4unl.minecraft.sqe.network.rcon.RConThreadQuery.parseIncomingPacket(RConThreadQuery.java:153)
[20:39:39] [Query Listener #42/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at k4unl.minecraft.sqe.network.rcon.RConThreadQuery.run(RConThreadQuery.java:330)
[20:39:39] [Query Listener #42/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at java.lang.Thread.run(Thread.java:745)
[20:39:39] [Query Listener #42/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.ClassNotFoundException: k4unl.minecraft.k4lib.network.EnumQueryValues
[20:39:39] [Query Listener #42/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[20:39:39] [Query Listener #42/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[20:39:39] [Query Listener #42/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[20:39:39] [Query Listener #42/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:    ... 3 more
[20:39:39] [Query Listener #42/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.NullPointerException`

**Comment by K-4U** [comment]
Wow that is a long log.
Next time please upload it to pastebin ;)

In term of your error: Did you install the proper K4Lib version?
What versions are you running? Forge, Minecraft, SIP and K4Lib?

**Comment by DannielDVH** [comment]
Sorry, i updated.
Minecraft 1.7.10
Forge Mod Loader version: 7.99.40.1614
SIP:  1.0.7-universal.jar
K4LIB: 0.1.46-universal.jar

**Comment by DannielDVH** [comment]
I see that it opens the listener in 25565, i tried now with python and php and it's not working and it gives me the error from the begging of the theard

**Comment by K-4U** [comment]
Try updating for a bit. There's a newer version for SIP, 1.0.8,
Also a few newer versions for K4Lib. See if the problem persists.

**Comment by DannielDVH** [comment]
SIP 1.0.8 isn't for MC 1.10?

**Comment by K-4U** [comment]
You mean 1.7.10?

**Comment by DannielDVH** [comment]
https://minecraft.curseforge.com/projects/serverinfoprovider/files
I see only 2 versions compatible for 1.7.10
SIP 1.0.8 is compatible with 1.10

**Comment by K-4U** [comment]
Yessss you are correct.
i was looking at the wrong project.. Still, it looks like the problem is K4Lib related, so try to update that one.

**Comment by DannielDVH** [comment]
Updated to k4lib-1.7.10-0.1.57-universal.jar

> 
[21:02:01] [Query Listener #42/INFO] [SQE]: Packet len 7 [/86.126.23.76:5939]
[21:02:01] [Query Listener #42/INFO] [SQE]: Packet '09' [/86.126.23.76:5939]
[21:02:01] [Query Listener #42/INFO] [SQE]: Challenge [/86.126.23.76:5939]
[21:02:02] [Query Listener #42/INFO] [SQE]: Packet len 11 [/86.126.23.76:5939]
[21:02:02] [Query Listener #42/INFO] [SQE]: Packet '08' [/86.126.23.76:5939]
[21:02:02] [Query Listener #42/INFO] [SQE]: Asked for the special packet!
[21:02:02] [Query Listener #42/INFO] [SQE]: RECV:
[21:02:02] [Query Listener #42/INFO] [SQE]: {
  "misformed": "MISFORMED JSON"
}
[21:02:02] [Query Listener #42/INFO] [SQE]: Status [/86.126.23.76:5939]
[21:02:02] [Query Listener #42/INFO] [SQE]: Challenge [/86.126.23.76:5939]
> 


And when i run py script:

> 
Ctrl-C to exit
Connecting to UDP
Connected to UDP, asking for the port

Traceback (most recent call last):
  File "/Users/danniel/Desktop/as.py", line 26, in <module>
    port = int(port)
ValueError: invalid literal for int() with base 10: '{\n  "misformed": "MISFORMED JSON"\n}'

>

**Comment by K-4U** [comment]
Ah yes. In the 1.7 version there was no automatic port-searching yet.. 

Luckily, somebody else managed to snatch the script for you: https://github.com/Zvarpensg/TripleSRuby/blob/minecraft/plugins/minecraft.py Try running this script.

**Comment by DannielDVH** [comment]
Traceback (most recent call last):
  File "/Users/danniel/Desktop/as.py", line 151, in <module>
    q = MCQuery(host, port)
  File "/Users/danniel/Desktop/as.py", line 23, in __init__
    self.handshake()
  File "/Users/danniel/Desktop/as.py", line 37, in handshake
    self.write_packet(9, '')
  File "/Users/danniel/Desktop/as.py", line 26, in write_packet
    o = '\xFE\xFD' + struct.pack('>B', type).decode('UTF-8') + struct.pack('>l', self.id).decode('UTF-8') + payload
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfe in position 0: ordinal not in range(128)
>>> 


But for php version why i get only Warning: array_key_exists() expects parameter 2 to be array, null given in SIPRequester.class.php line 99

**Comment by K-4U** [comment]
I will have a look tomorrow

**Comment by DannielDVH** [comment]
Ok thank you :)

**Comment by K-4U** [comment]
So having updated the actual 1.7 version.. Could you try again with the new python script? :D
